on:
  push:
    branches:
      - main
name: ðŸš€ Deploy Website on push to namecheap hosting
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to host
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4

    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.whattodo.tech
        username: public_ftp@whattodo.tech
        password: '!whattodo265'
        protocol: ftps
        security: strict
